# city builder, survival horror, rts, colony sim, tower defense

In [1]:
# Firstly, we will need to import all the required libraries to proceed with the data analysis
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

# Setting the option to see all the columns in the preview to ensure all information is captured
pd.set_option('display.max_columns', None)

In [2]:
# We will now read in the file
try:
    games_data = pd.read_csv("games.csv")
except FileNotFoundError:
    print("\n!ERROR!" \
    "\nThe file you're trying to load is not found. Make sure to check the spelling and " \
    "punctuation and try again")
    raise SystemExit("Stop right there! Please see the error message above!")

In [3]:
# Proceeding to previewing the data to estimate what can be deleted
games_data.head(15)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,Full audio languages,Reviews,Header image,Website,Support url,Support email,Windows,Mac,Linux,Metacritic score,Metacritic url,User score,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com,True,False,False,0,NaN,0,252,3,NaN,0,231,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net,True,True,False,0,NaN,0,21,3,NaN,0,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],['Korean'],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,yujingamesc@gmail.com,True,False,False,0,NaN,0,0,0,NaN,19,0,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],['English'],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1654170,Agony VR,"Apr 5, 2023",0 - 20000,0,0,13.99,0,0,A JOURNEY THROUGH HELL! Explore the most terri...,"['English', 'French', 'Italian', 'German', 'Sp...","['English', 'Turkish']",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,https://www.ignibit.com/,office@ignibit.com,True,False,False,0,NaN,0,0,0,NaN,0,0,The trailer and the screenshots may contain co...,0,0,0,0,Ignibit,"Ignibit,Madmind Studio","Single-player,Tracked Controller Support,VR On...","Action,Adventure",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1934300,Armored Brigade II,"Apr 8, 2025",0 - 20000,8,0,35.99,10,1,Building on the success of its acclaimed prede...,['English'],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,support@slitherine.co.uk,True,False,False,0,NaN,0,117,13,NaN,0,107,NaN,675,0,1253,0,Veitikka Studios,Matrix Games,"Single-player,Steam Workshop,Steam Cloud,Famil...","Simulation,Strategy","Simulation,Strategy,RTS,Wargame,Grand Strategy...",https://shared.akamai.steamstatic.com/store_it...,NaN
700340,Galacatraz: Eject Equip Escape,"Feb 1, 2018",0 - 20000,0,0,0.99,0,0,"Years ago, Ricardo Luger was in the wrong plac...",['English'],['English'],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,http://www.summerbearstudio.com,support@summerbearstudio.com,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,Summer Bear Studio,Summer Bear Studio,"Single-player,Full controller support,Family S...","Action,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1157670,Hepta Beats,"May 7, 2021",0 - 20000,0,0,0.99,0,0,Hepta Beats is a 2D side-view platformer game ...,"['English', 'French', 'Italian', 'German', 'Sp...","['English', 'French', 'Italian', 'German', 'Sp...",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,heptabeats@gmail.com,True,False,False,0,NaN,0,28,4,NaN,9,0,NaN,0,0,0,0,Matheus Bigatão,Matheus Bigatão,"Single-player,Steam Achievements,Full controll...","Casual,Indie","Precision Platformer,Rhythm,Music,Difficult,Ab...",https://shared.akamai.steamstatic.com/store_it...,NaN
1540330,MUMBA IV: Egypt Jewels,"Dec 13, 2021",0 - 20000,1,0,0.59,0,1,WARRNING Don't show Your mom this game. You kn...,"['English', 'French', 'Italian', 'German', 'Sp...",[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://airem.pl,http://airem.pl,info@airem.pl,True,True,True,0,NaN,0,19,6,NaN,100,0,NaN,0,0,0,0,Airem,Airem,"Single-player,Steam Achievements,Full controll...","Action,Casual,Indie,Strategy","Casual,Action,Strategy,Puzzle,Match 3,Singlepl...",https://shared.akamai.steamstatic.com/store_it...,NaN
1946890,Codename: Warlock Playtest,"Mar 25, 2022",0 - 0,0,0,0.00,0,0,NaN,[],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1108640,OMNIMUS,"Sep 25, 2019",0 - 20000,0,0,0.99,0,1,Omnimus is an interactive visual novel in an u...,"['English', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,https://vk.com/badnovells,NaN,letodigest@gmail.com,True,True,True,0,NaN,0,47,6,NaN,0,0,NaN,0,0,0,0,Angry games,Total,"Single-player,Family Sharing","Adventure,Indie","Adventure,Indie,Visual Novel,Interactive Ficti...",https://shared.akamai.steamstatic.com/store_it...,NaN
1025440,Fantasy General II,"Sep 5, 2019",100000 - 200000,13,0,13.99,0,4,Three hundred years have passed since the Shad...,"['English', 'German', 'Spanish - Spain', 'Simp...",[],“And this is the very reason why I believe Fan...,https://shared.akamai.steamstatic.com/store_it...,http://www.slitherine.com/,http://www.slitherine.com/,support@slitherine.co.uk,True,False,False,80,https://www.metacritic.com/game/pc/fantasy-gen...,0,1025,210,NaN,77,994,NaN,489,0,52,0,Owned by Gravity,Slitherine Ltd.,"Single-player,Multi-player,PvP,Online PvP,Stea...",Strategy,"Strategy,Turn-Based Strategy,Fantasy,Turn-Base...",https://shared.akamai.steamstatic.com/store_it...,NaN
2113450,"Forests, Fields and Fortresses","Apr 5, 2023",0 - 20000,0,0,1.49,70,0,"Forests, Fields and Fortresses is a mix of a p...","['English', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://9eyesgs.com/,http://9eyesgs.com/,support@9eyesgs.com,True,True,False,0,NaN,0,64,2,NaN,13,0,NaN,0,0,0,0,9 Eyes Game Studio,"9 Eyes Game Studio,Stately Snail","Single-player,Steam Achievements,Partial Contr...","Casual,Indie","Casual,Strategy,Puzzle,City Builder,Tabletop,B...",https://shared.akamai.steamstatic.com/store_it...,NaN
2922740,DogDogDog,"Apr 19, 2024",0 - 20000,0,0,1.35,66,0,'DogDogDog' is a horror adventure game set in ...,"['English', 'Simplified Chinese', 'Japanese', ...",[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,nowar1112@hotmail.com,True,False,False,0,NaN,0,34,10,NaN,5,0,"gore,blood",0,0,0,0,LuuuLuuuL,LuuuLuuuL,"Single-player,Steam Achievements,Full controll...","Adventure,Casual,Indie","Dog,Cute,Walking Simulator,Psychological Horro...",https://shared.akamai.steamstatic.com/store_it...,NaN

In [4]:
# Checking that the last column consists of only NaN
games_data["Movies"].isna().all()

np.True_

### From the preview we can clearly see the initial issue with the data, as the two columns merged into one (DiscountDCL count) causing a shift of the data. The dataframe also did not read the AppID correctly, leading to a skeweness of the dataframe by one column to the left causing the 'Movies' column to be completely NaN. We will need to address this before proceeding with the further analysis

In [5]:
# We will need to get the names of the columns to confirm this hypothesis and proceed with the 
# data transformation
cols = games_data.columns.tolist()
print(cols)

['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DiscountDLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

In [6]:
# Proceeding with the fixing and separating the columns to reflect the data correctly
fixed = []
for col in cols:
    if col == 'DiscountDLC count':
        fixed += ['Discount', 'DLC count']
    else:
        fixed.append(col)

games_data = pd.read_csv('games.csv', header=0, names=fixed)
print(games_data.columns.to_list())

['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'Discount', 'DLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

In [7]:
# Checking that the fix worked and the data is now presented correctly
games_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,Supported languages,Full audio languages,Reviews,Header image,Website,Support url,Support email,Windows,Mac,Linux,Metacritic score,Metacritic url,User score,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com,True,False,False,0,NaN,0,252,3,NaN,0,231,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net,True,True,False,0,NaN,0,21,3,NaN,0,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],['Korean'],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,yujingamesc@gmail.com,True,False,False,0,NaN,0,0,0,NaN,19,0,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],['English'],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

Now that we've got all the columns aligned with the correct representative information we will proceed with further evaluating the data and ensuring the data is being shown correctly

In [9]:
games_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125855 non-null  int64
 1   Name                        125854 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  str
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  int64
 6   Price                       125855 non-null  float64
 7   Discount                    125855 non-null  int64
 8   DLC count                   125855 non-null  int64
 9   About the game              117393 non-null  str
 10  Supported languages         125855 non-null  str
 11  Full audio languages        125855 non-null  str
 12  Reviews                     12181 non-null   str
 13  Header image                125774 non-null  str
 14  Website                     50520 non-null   str
 15  Support url                 55295 non-null   str
 16  Support email               103225 non-null  str
 17  Windows                     125855 non-null  bool
 18  Mac                         125855 non-null  bool
 19  Linux                       125855 non-null  bool
 20  Metacritic score            125855 non-null  int64
 21  Metacritic url              4258 non-null    str
 22  User score                  125855 non-null  int64
 23  Positive                    125855 non-null  int64
 24  Negative                    125855 non-null  int64
 25  Score rank                  40 non-null      float64
 26  Achievements                125855 non-null  int64
 27  Recommendations             125855 non-null  int64
 28  Notes                       23310 non-null   str
 29  Average playtime forever    125855 non-null  int64
 30  Average playtime two weeks  125855 non-null  int64
 31  Median playtime forever     125855 non-null  int64
 32  Median playtime two weeks   125855 non-null  int64
 33  Developers                  117406 non-null  str
 34  Publishers                  116933 non-null  str
 35  Categories                  116889 non-null  str
 36  Genres                      117432 non-null  str
 37  Tags                        83353 non-null   str
 38  Screenshots                 119828 non-null  str
 39  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 403.9 MB

In [ ]:
'''for column in games_data.columns:
    print(f"Unique values for {column} are: ")
    print(games_data[column].unique())
    print("----------------------------------------------")'''

Unique values for AppID are:
[2539430  496350 1034400 ... 3788650 3509140 4247310]
----------------------------------------------
Unique values for Name are:
<ArrowStringArray>
[           'Black Dragon Mage Playtest',
 'Supipara - Chapter 1 Spring Has Come!',
     'Mystery Solitaire The Black Raven',
           '버튜버 파라노이아 - Vtuber Paranoia',
                         'Maze Quest VR',
                              'Agony VR',
                    'Armored Brigade II',
        'Galacatraz: Eject Equip Escape',
                           'Hepta Beats',
                'MUMBA IV: Egypt Jewels',
 ...
                         'Quirky Cabbie',
                      'Automatic Eltron',
                           'Metal Goose',
             'Libertine: King of Hearts',
                        'Dungeon Armory',
                      'Sotsugyo Omedeto',
                       'Island on cloud',
                          'Rosie Planet',
            'Fear Effect 2: Retro Helix',
                     'Project Liminal 2']
Length: 124645, dtype: str
----------------------------------------------
Unique values for Release date are:
<ArrowStringArray>
[ 'Aug 1, 2023', 'Jul 29, 2016',  'May 6, 2019', 'Oct 31, 2024',
 'Apr 24, 2025',  'Apr 5, 2023',  'Apr 8, 2025',  'Feb 1, 2018',
  'May 7, 2021', 'Dec 13, 2021',
 ...
 'Feb 21, 2026', 'Feb 23, 2026', 'Feb 22, 2026', 'Feb 24, 2026',
  'Dec 1, 2026', 'Feb 25, 2026', 'Feb 27, 2026',  'Mar 1, 2026',
  'Mar 2, 2026', 'Jun 30, 2026']
Length: 5141, dtype: str
----------------------------------------------
Unique values for Estimated owners are:
<ArrowStringArray>
[                '0 - 0',             '0 - 20000',       '100000 - 200000',
      '500000 - 1000000',         '20000 - 50000',       '200000 - 500000',
        '50000 - 100000',     '2000000 - 5000000',   '10000000 - 20000000',
     '1000000 - 2000000',   '20000000 - 50000000',    '5000000 - 10000000',
 '100000000 - 200000000',  '50000000 - 100000000']
Length: 14, dtype: str
----------------------------------------------
Unique values for Peak CCU are:
[   0    1    8 ...  352 1050 1756]
----------------------------------------------
Unique values for Required age are:
[ 0 17 18 13 12  3 16 10  6  1  7 14 15 20 21]
----------------------------------------------
Unique values for Price are:
[0.0000e+00 5.2400e+00 4.9900e+00 8.9900e+00 1.3990e+01 3.5990e+01
 9.9000e-01 5.9000e-01 1.4900e+00 1.3500e+00 1.4000e+00 1.0400e+00
 5.9900e+00 7.9900e+00 2.9900e+00 1.9900e+00 1.2490e+01 9.9900e+00
 4.9000e-01 1.3900e+00 4.7900e+00 3.4900e+00 8.9000e-01 7.9000e-01
 2.4900e+00 1.0040e+01 4.0000e+00 3.5900e+00 7.4900e+00 5.5900e+00
 1.1690e+01 1.5900e+00 1.4990e+01 1.1990e+01 1.0990e+01 3.9900e+00
 1.0390e+01 3.7400e+00 3.3900e+00 3.6900e+00 1.7400e+00 6.9900e+00
 2.0900e+00 1.1900e+00 6.4900e+00 6.9000e-01 2.9990e+01 3.4990e+01
 1.9990e+01 5.5000e-01 3.1900e+00 1.3400e+00 7.6900e+00 5.9100e+00
 2.3900e+00 1.5990e+01 6.0000e-01 8.3900e+00 3.1490e+01 9.8000e-01
 1.2400e+00 3.8900e+00 1.6990e+01 6.5000e+00 2.6900e+00 7.4000e-01
 2.2490e+01 7.1900e+00 5.9990e+01 9.8800e+00 6.6000e-01 2.7990e+01
 9.0900e+00 5.4990e+01 4.4900e+00 9.7400e+00 9.8900e+00 4.3900e+00
 1.2990e+01 9.2000e-01 1.9999e+02 5.4000e-01 1.8740e+01 5.0900e+00
 3.8400e+00 1.0000e+00 2.2400e+00 2.7900e+00 1.7900e+00 1.0900e+00
 4.9990e+01 4.8900e+00 8.2400e+00 1.7990e+01 1.3490e+01 2.6990e+01
 5.5100e+00 4.5400e+00 1.6900e+00 1.7500e+00 6.2900e+00 4.2400e+00
 2.5400e+00 3.2900e+00 9.3000e-01 8.4000e-01 2.7400e+00 5.0000e-01
 2.4990e+01 3.9400e+00 9.5900e+00 2.3990e+01 1.2470e+01 9.3400e+00
 9.0000e-01 1.1400e+00 8.0000e-01 5.3900e+00 1.5190e+01 6.8000e-01
 7.9400e+00 7.4500e+00 4.9500e+00 8.0900e+00 7.7900e+00 2.4490e+01
 4.9300e+00 5.8400e+00 7.1000e-01 1.2790e+01 1.2300e+00 6.3900e+00
 6.2400e+00 4.1900e+00 2.3300e+00 6.7400e+00 1.0490e+01 1.9490e+01
 1.8990e+01 2.5900e+00 9.5000e-01 7.7000e-01 3.0100e+00 1.8700e+00
 2.0000e+00 1.8300e+00 2.1600e+00 3.8490e+01 1.4690e+01 1.7000e+00
 3.3400e+00 3.1400e+00 1.2590e+01 1.1590e+01 1.2900e+00 3.5000e+00
 1.9500e+00 1.9790e+01 1.0100e+00 1.1240e+01 1.6190e+01 1.9700e+00
 7.2000e+00 1.7490e+01 3.2400e+00 2.9100e+00 1.6240e+01 2.4500e+00
 4.9400e+00 3.0400e+00 4.7990e+01 2.4200e+00 3.9500e+00 6.5900e+00
 9.9000e+00 1.4400e+00 1.1390e+01 7.6000e-01 1.1300e+00 8.7900e+00
 3.9990e+01 2.7100e+00 4.0700e+00 1.3860e+01 4.5900e+00 5.4900e+00
 1.9400e+00 6.7000e-01 1.1890e+01 5.3000e-01 4.0400e+00 3.2000e+00
 9.7000e-01 1.2700e+00 1.6070e+01 3.1990e+01 1.8800e+00 3.9100e+00
 2.3390e+01 2.1400e+00 5.1900e+00 5.9400e+00 4.3300e+00 8.4400e+00
 6.1900e+00 5.0000e+00 1.5500e+00 7.5000e-01 1.5400e+00 6.7900e+00
 7.3900e+00 8.5000e-01 4.3990e+01 4.2490e+01 1.3700e+00 1.2740e+01
 6.8300e+00 2.0990e+01 6.9990e+01 7.6400e+00 3.3300e+00 1.1550e+01
 3.7490e+01 5.2000e+00 6.5000e-01 9.4900e+00 1.2640e+01 8.4900e+00
 7.3000e-01 1.9100e+00 1.7760e+01 1.3390e+01 7.0000e-01 6.4000e-01
 1.6400e+00 1.5000e+00 6.0200e+00 1.3300e+00 2.0090e+01 2.4400e+00
 9.0000e+00 2.3500e+00 2.1900e+00 3.7900e+00 5.7000e-01 1.9240e+01
 2.3100e+00 8.5700e+00 8.7000e-01 1.3740e+01 7.5900e+00 8.3000e-01
 2.5990e+01 1.0500e+01 6.6900e+00 1.0700e+00 4.4990e+01 1.2340e+01
 7.1400e+00 1.0340e+01 1.3670e+01 7.9600e+00 3.2300e+00 2.5000e+00
 1.3290e+01 1.1040e+01 3.8600e+00 7.9100e+00 8.2500e+00 8.7400e+00
 3.5100e+00 6.6200e+00 6.1000e-01 4.4100e+00 4.3400e+00 1.5890e+01
 1.4390e+01 1.2630e+01 1.2310e+01 2.2900e+00 6.0000e+00 1.0000e+01
 1.2800e+00 1.3790e+01 9.7900e+00 3.0000e+00 1.2720e+01 4.1990e+01
 2.6300e+00 6.3100e+00 4.5500e+00 2.5490e+01 6.2000e+00 4.6800e+00
 5.1000e-01 5.9300e+00 8.1000e-01 4.8990e+01 5.3500e+00 1.0790e+01
 5.2100e+00 4.0900e+00 2.5100e+00 5.0300e+00 1.2240e+01 1.5290e+01
 2.0000e+01 1.2820e+01 9.9990e+01 1.0190e+01 3.9590e+01 3.4000e+00
 2.4800e+00 4.2900e+00 5.9500e+00 1.1100e+00 4.2300e+00 1.0430e+01
 7.9990e+01 2.3700e+00 9.3500e+00 1.6700e+00 8.0000e+00 1.3100e+00
 1.6000e+00 7.3400e+00 6.3000e+00 1.6490e+01 4.0190e+01 3.1100e+00
 4.0590e+01 8.6000e-01 1.4500e+00 2.9600e+00 1.7300e+00 1.8590e+01
 2.6240e+01 2.5000e+01 8.7500e+00 5.1100e+00 1.1000e+01 1.6740e+01
 7.3600e+00 4.0500e+00 7.2000e-01 9.4300e+00 1.1190e+01 2.8900e+00
 6.0800e+00 4.0100e+00 2.8000e+00 2.5700e+00 5.4000e+00 9.9500e+00
 8.8800e+00 4.5000e+00 1.5000e+01 2.0300e+00 4.0200e+00 1.2600e+00
 1.3190e+01 1.2000e+00 5.8900e+00 3.7700e+00 2.9240e+01 7.8200e+00
 4.9000e+00 6.9000e+00 6.1700e+00 3.3990e+01 4.1300e+00 2.5800e+00
 1.1999e+02 1.4200e+01 1.4500e+01 4.6300e+00 3.1200e+00 9.3700e+00
 5.8000e-01 6.2000e-01 4.8500e+00 1.4440e+01 4.9700e+00 3.4400e+00
 4.4000e+00 1.6790e+01 1.4250e+01 3.0900e+00 2.8400e+00 1.2120e+01
 8.1100e+00 8.0400e+00 4.9100e+00 9.4000e-01 1.2000e+01 1.3590e+01
 4.8000e+00 1.2950e+01 9.2900e+00 2.2390e+01 1.9800e+00 8.7000e+00
 4.4400e+00 4.8300e+00 8.9600e+00 2.8700e+00 4.7400e+00 8.0300e+00
 5.9000e+00 1.2500e+00 2.1240e+01 1.2200e+00 1.4200e+00 1.0710e+01
 9.6000e-01 5.6600e+00 8.9990e+01 6.4500e+00 1.0720e+01 8.3600e+00
 2.1590e+01 2.2990e+01 1.7240e+01 1.2890e+01 8.2200e+00 3.8990e+01
 6.4990e+01 1.6300e+00 3.0300e+00 5.5990e+01 1.5300e+00 3.8240e+01
 2.1990e+01 1.4900e+01 6.6600e+00 1.6140e+01 7.7400e+00 9.9700e+00
 3.0140e+01 8.8100e+00 5.6000e+00 1.0530e+01 2.7490e+01 2.2790e+01
 5.7500e+00 2.4000e+00 3.5600e+00 1.1500e+00 2.3000e+00 1.7090e+01
 1.0230e+01 8.3300e+00 1.1600e+00 7.0300e+00 9.6900e+00 9.8500e+00
 4.8600e+00 1.9190e+01 1.1400e+01 1.4100e+00 2.6650e+01 5.9950e+01
 1.2999e+02 2.2300e+00 4.9600e+00 1.4240e+01 2.9740e+01 2.9500e+00
 2.4740e+01 7.1100e+00 3.8500e+00 7.9200e+00 1.4940e+01 1.5600e+00
 1.1249e+02 1.6000e+01 8.1300e+00 3.2100e+00 1.4090e+01 5.2000e-01
 5.1200e+00 1.8400e+00 8.5400e+00 1.7100e+00 2.9300e+00 2.2100e+00
 2.4700e+00 2.9000e+00 1.3100e+01 2.8490e+01 2.5200e+00 9.3900e+00
 3.2490e+01 1.0640e+01 2.2480e+01 1.7599e+02 2.9390e+01 7.2200e+00
 2.2700e+00 3.6800e+00 1.5700e+00 1.4300e+00 3.2800e+00 2.0240e+01
 3.6000e+00 5.3100e+00 1.4380e+01 1.4700e+00 3.7470e+01 7.8900e+00
 9.3600e+00 1.6090e+01 5.5400e+00 7.7700e+00 3.3740e+01 1.3910e+01
 9.4400e+00 1.9740e+01 3.0000e+01 2.5190e+01 1.8690e+01 1.4600e+00
 6.8900e+00 1.3200e+00 9.0600e+00 2.7190e+01 1.0500e+00 2.1000e+00
 5.7300e+00 5.2700e+00 6.6800e+00 1.3000e+00 8.6900e+00 5.9490e+01
 6.9500e+00 1.2050e+01 7.0000e+00 1.2910e+01 4.3100e+00 5.3990e+01
 2.3590e+01 2.6700e+00 4.6400e+00 3.3500e+00 4.6700e+00 1.7600e+00
 5.5000e+00 5.6900e+00 2.3090e+01 1.1000e+00 3.6300e+00 9.4800e+00
 3.0500e+00 2.5200e+01 1.4490e+01 1.8500e+00 3.7100e+00 5.0000e+02
 7.6700e+00 1.8900e+00 4.2000e+00 1.0440e+01 5.2900e+00 6.2300e+00
 3.2200e+00 1.7200e+00 2.2740e+01 7.0200e+00 6.2200e+00 3.6300e+01
 5.3000e+00 7.2500e+00 9.9900e+02 1.9690e+01 4.3700e+00 1.4920e+01
 6.6400e+00 9.1900e+00 8.2700e+00 2.0400e+00 1.9920e+02 1.4999e+02
 1.9920e+01 3.1600e+00 2.3200e+00 1.4980e+01 1.7590e+01 1.0780e+01
 1.4190e+01 1.6100e+00 1.4840e+01 1.1200e+00 1.8000e+00 1.1250e+01
 5.5600e+00 4.4700e+00 1.7600e+01 1.0300e+00 4.4200e+00 2.9700e+00
 1.0940e+01 7.4600e+00 7.2900e+00 5.0800e+00 4.8800e+00 7.4990e+01
 1.1090e+01 9.9998e+02 4.6100e+00 1.7790e+01 5.5800e+00 3.0700e+00
 8.1900e+00 9.6800e+00 5.2490e+01 1.7800e+00 1.1940e+01 1.4790e+01
 2.8500e+00 2.3600e+00 2.2220e+01 1.1540e+01 1.1800e+00 3.2990e+01
 1.3500e+01 2.0600e+00 9.1400e+00 8.5900e+00 8.8000e-01 3.3490e+01
 7.5000e+00 7.4700e+01 1.8100e+00 4.1000e+00 3.9000e+00 1.0999e+02
 1.3600e+00 4.4300e+00 8.8300e+00 9.6500e+00 4.2500e+00 2.1500e+00
 1.6800e+01 1.2100e+00 5.7900e+00 8.1600e+00 2.2000e+00 6.8100e+00
 1.1840e+01 2.3440e+01 1.1490e+01 4.1200e+00 3.6400e+00 6.0900e+00
 2.6600e+00 9.8700e+00 1.4290e+01 2.9400e+00 1.5200e+00 1.0950e+01
 7.4700e+00 3.6700e+00 1.5740e+01 1.8200e+00 2.5930e+01 4.7300e+00
 2.2190e+01 8.9000e+00 8.5000e+00 5.6400e+00 6.7990e+01 5.4300e+00
 6.1100e+00 5.2300e+00 1.2060e+01 3.0390e+01 2.7500e+00 1.1700e+00
 1.0020e+01 1.2900e+01 3.5500e+00 4.5300e+00 1.6370e+01 7.5100e+00
 1.7500e+01 2.4300e+00 1.1910e+01 6.9200e+00 8.5100e+00 3.1000e+00
 6.0400e+00 1.3580e+01 6.7100e+00 1.1710e+01 5.9600e+00 2.6400e+00
 5.0990e+01 2.2040e+01 5.5200e+00 7.4000e+00 2.5500e+00 2.6250e+01
 2.3400e+00 1.1560e+01 7.0900e+00 1.5040e+01 3.9800e+00 5.3800e+00
 8.3990e+01 1.2390e+01 7.8100e+00 3.9700e+00 2.1300e+00 6.5600e+00
 5.8300e+00 5.4500e+00 2.1700e+00 5.0600e+00 1.9940e+01 3.4100e+00
 6.4700e+00 2.7800e+00 8.8700e+00 7.2100e+00 5.8700e+00 1.5100e+00
 7.8300e+00 9.1000e-01 1.9800e+01 1.9950e+01 1.0260e+01 6.7000e+00
 3.2500e+00 1.3240e+01 3.4700e+00 1.4050e+01 5.2500e+00 3.8300e+00
 8.3200e+00 1.1790e+01 1.0540e+01 4.7500e+00 1.9900e+01 6.6500e+00
 3.7300e+00 9.9950e+01 1.0800e+00 1.3250e+01 3.2000e+01 4.6890e+01
 2.9800e+00 2.4600e+00 4.0800e+00 1.9000e+00 6.5500e+00 5.6700e+00
 2.2500e+00 1.2750e+01 2.7700e+00 4.5490e+01 3.0090e+01 2.6260e+01
 4.7200e+00 5.4800e+00 6.1600e+00 7.1200e+00 8.4990e+01 5.3200e+00
 2.0700e+00 8.9500e+00 5.9000e+01 2.2000e+01 1.3330e+01 1.3000e+01
 3.7600e+00 6.1500e+00 5.1990e+01 1.1430e+01 6.0100e+00 4.5800e+00
 1.4000e+01 1.0210e+01 1.4590e+01 4.2600e+00 5.7700e+00 1.7000e+01
 2.9999e+02 1.0770e+01 1.3999e+02 2.2200e+00 1.4320e+01 8.4000e+00
 2.8200e+00 1.4740e+01 8.2000e-01 2.4890e+01 1.7390e+01 6.3600e+00
 9.4700e+00 2.0500e+01 3.0790e+01 1.6900e+01 1.6500e+00 1.0800e+01
 1.2749e+02 5.7400e+00 5.1700e+00 3.8200e+00 5.3600e+00 2.9990e+02
 6.4400e+00 8.0500e+00 1.6600e+00 2.8800e+00 1.0590e+01 2.4970e+01
 1.0910e+01 8.6300e+00 4.8400e+00 9.5000e+00 3.5400e+00 1.5830e+01
 9.5600e+00 3.4800e+00 2.7200e+00 3.0600e+00 4.3000e+00 5.5500e+00
 3.4500e+00 3.9000e+01 1.2430e+01 9.1100e+00 4.1700e+00 1.1050e+01
 3.2700e+00 4.4500e+00 5.5700e+00 5.2600e+00 1.5490e+01 4.6500e+00
 1.2499e+02 3.3100e+00 1.8710e+01 1.2020e+01 1.8190e+01 1.5590e+01
 2.4950e+01 7.2400e+00 5.2200e+00 1.5800e+00 7.4800e+00 1.0200e+00
 7.7990e+01 4.3600e+00 3.3700e+00 8.3100e+00 6.8200e+00 9.2300e+00
 7.8000e-01 3.5000e+01 1.8890e+01 7.9500e+00 3.8000e+00 3.0760e+01
 5.6000e-01 2.0800e+01 1.0870e+01 3.8700e+00 1.3310e+01 2.6100e+00
 2.3000e+01 2.8000e+01 2.6390e+01 1.5750e+01 4.2800e+00 5.7000e+00
 4.5100e+00 9.6300e+00 2.7780e+01 2.6999e+02 1.1330e+01 4.9000e+01
 7.1000e+00 3.1500e+00 1.5390e+01 5.7100e+00 6.1200e+00 2.6790e+01
 1.9590e+01 1.3340e+01 6.3000e-01 4.7690e+01 1.0840e+01 3.1800e+00
 1.1380e+01 6.5700e+00 5.3300e+00 9.9800e+00 7.3500e+00 1.3800e+00
 3.4640e+01 3.4190e+01 1.8290e+01 5.3400e+00 1.9200e+00 3.6200e+00
 4.7800e+00 7.3700e+00 1.8240e+01 3.3000e+00 1.6000e+02 6.0700e+00
 1.6390e+01 8.6800e+00 9.1000e+00 3.3800e+00 2.4460e+01 1.9540e+01
 3.6100e+00 1.1300e+01 1.0070e+01 2.1800e+00 5.9700e+00 4.6900e+00
 6.8800e+00 3.4970e+01 3.4300e+00 9.8300e+00 9.6000e+00 4.8740e+01
 3.5200e+00 6.0490e+01 2.0200e+00 2.9900e+01 9.7500e+00 5.1500e+00
 2.0100e+00 2.3800e+01 1.1800e+01 1.1750e+01 2.7600e+00 3.8100e+00
 1.0550e+01 1.6820e+01 2.4030e+01 6.6300e+00 4.9490e+01 2.7000e+00
 3.7800e+00 1.8000e+01 2.7640e+01 6.7490e+01 8.8900e+00]
----------------------------------------------
Unique values for Discount are:
[  0  65  10  70  66  80  33  50  51  30  75  15  60  25  90  20  85  40
  35  69  45  89  84  72  95  21  67  55  22  28  77  87  94  83  47  38
  76  88  68  61  12  34  27  39  81  78  91  86  79  24  73  26  52  93
  63  44  92  42 100  36  64  23  31  48  59  62  13  49  58  82  37  46
  54  32  56  57  74  71  41  43  29  14  18  53  17  16  11  19]
----------------------------------------------
Unique values for DLC count are:
[   0    1    4    3    5    8   12   22    2    6    7   10   96   11
  105   16    9  190   38   59   20   18   14   26   13   23   58   79
   29   24  101  112   25   46   30   21   17   51   44   35   80   37
   32  100   15   84   57   74  168  448   36   64   68  181   33  875
   19   43   71   52   39   55   47   28   50   31  167   66   67  314
   42   49   27  176   90   41  782   92   72   83  103   61   34  200
   77   54  234   73   70   60  120  149  272   81   99   65  129  261
   45 2006  967  142   53   97   62  110   56   86  316   40  461   69
 1066  252  159  311 3703]
----------------------------------------------
Unique values for About the game are:
<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    nan,